### ISSUE TITLE
Cache intermediates when build fails

### ISSUE THREAD

**Issue by dprotaso** [bazel-contrib/setup-bazel#75]
I'm trying to build a fork of https://github.com/envoyproxy/envoy/ in my own repository. I'm hoping to use this action so that caching can improve build times.

I'm hitting timeouts on GitHub's hosted runners - retriggering the job I would assume the units that were compiled in earlier runs would have been cached but I notice they are not.

I'm using the following config

```yaml
    - uses: bazel-contrib/setup-bazel@0.14.0
      with:
        bazelisk-cache: true
        repository-cache: true
        external-cache: true
        disk-cache: ${{ github.workflow }}
```

Does this action save the cache on failed workflows?
